### PR TITLE
code added

### PR DESCRIPTION
**Pull request by bellom**
Kindly review the code
Thanks.

### CODE REVIEW

**Comment by dipto0321** [comment]
Hi @bellom ,

Again good job. It perfectly works for an array. But what about `Hash`? Original Enumerable also work for `Hash`. Take a look at [this ](https://prnt.sc/n7kv4l). I will recommend you also try for hash. Because it will help you to grasp the `Enumerable` methods behavior for `hash`.
Again, for the array, it works perfectly. 
Please send another request to review code after adding `hash` enumerable functionality. 

Thanks 🙏

**Comment by bellom** [comment]
Opps, will work on that now.
Thanks

**Comment by dipto0321** [comment]
Hi @bellom ,

Your methods work properly except my_map. Because you created a couple of my_map methods which is really confused for the ruby interpreter. There should be one my_map. Also, add hash functionality for all the methods. After all those things please add sample test for rest array and all hash like you did for the array (as I discussed with you on slack). You can discuss with other students and partners to understand. Let me know if you have any question just knock me on slack.

Please send another request to review and after submitting the form please knock me on slack so that before review I can discuss with you if there will any problem. Best of luck 🙂 

Thanks 🙏

**Comment by dipto0321** [comment]
Hi @bellom ,

Now it is working perfectly for an array. Still `my_count` not work for a block and I can't see that you accept block for this in your method. So please fixed it. 
Hash functionality only works for `my_each` except this other function not working. I can't access only `key` or `value` by your methods. So please again fix these issues. Check your output with the original output. Try to understand properly first how original methods work for hash. Then think about it. 

Send another request to review for this. Let me know if you have any question.

Thanks

**Comment by dipto0321** [comment]
Hi @bellom ,
Good job. Congratulation! I am pretty sure that you already achieved a good understanding of this topic.  So, you can merge now. This is from me 👍
Thanks 😌

**Pull request merged**
